baseURL = '/'
languageCode = 'zh'
title = 'Go 鲜为人知的角落'

publishDir = 'docs'

theme = "carte"

[params]
    [params.uweuwe]
        [params.uweuwe.toc]
            display = true # Possibile values: true | false
